USE DataWarehouseAnalytics


-- ###############################################
-- Database Exploration
-- ###############################################

-- Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore All Columns in the Database
USE DataWarehouseAnalytics
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

-- ###############################################
-- Dimensions Exploration
-- ###############################################

-- Explore All Countries our customers come from.
SELECT DISTINCT country
FROM gold.dim_customers

-- Explore All Categories "The Major Divisions"
SELECT DISTINCT category
FROM gold.dim_products

-- ###############################################
-- Date Exploration
-- ###############################################

-- Find the date of the first and last orders
SELECT
	MIN(order_date) AS first_order_date
	, MAX(order_date) AS last_order_date
	, DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS order_range_months
FROM gold.fact_sales

-- Find the youngest and the oldest customers
SELECT
	MIN(birthdate) AS oldest_customer
	, DATEDIFF(YEAR, MIN(birthdate), GETUTCDATE()) oldest_customer_years
	, MAX(birthdate) AS youngest_customer
	, DATEDIFF(YEAR, MAX(birthdate), GETUTCDATE()) youngest_customer_years
FROM gold.dim_customers

-- ###############################################
-- Measures Exploration
-- ###############################################
-- Find the Total Sales
SELECT
	SUM(sales_amount) AS total_sales
FROM gold.fact_sales

-- Find the average selling price
SELECT
	AVG(price) AS avg_price
FROM gold.fact_sales 

-- Find the total quantity of sales
SELECT
	SUM(FS.quantity)
FROM gold.fact_sales FS

-- Find the Total number of Orders
SELECT
	COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales

-- Find the Total number of Products
SELECT
	COUNT(DISTINCT product_key)
FROM gold.dim_products

-- Find the Total number of Customers
SELECT 
	COUNT(customer_key)
FROM gold.dim_customers


-- Find the Total number of Customers that have placed an order
SELECT
	COUNT(customer_key) AS total_customers
FROM gold.fact_sales

SELECT
	COUNT(DISTINCT customer_key) AS total_customers
FROM gold.fact_sales

-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
	UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
	UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales
	UNION ALL
SELECT 'Total No. Orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
	UNION ALL
SELECT 'Total No. Products' AS measure_name, COUNT(product_name) AS measure_value FROM gold.dim_products
	UNION ALL
SELECT 'Total No. Customers' AS measure_name, COUNT(customer_key) AS measure_value FROM gold.dim_customers


-- ###############################################
-- Magnitude Analysis
-- ###############################################
-- Aggregate of [Measure] By [Dimension]
-- Aggregate - sum, avg, et c.
-- Total Customers by Countries
SELECT
	country
	, COUNT(DISTINCT customer_id) AS customers_count	
	, COUNT(DISTINCT customer_key) AS customer_key_count
FROM gold.dim_customers
GROUP BY country
ORDER BY customers_count DESC

-- Total Customers by Gender
SELECT
	gender
	, COUNT(customer_key) AS customer_key_count
FROM gold.dim_customers
GROUP BY gender
ORDER BY customer_key_count DESC

-- Total Products by Category
SELECT
	category
	, COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average cost in each category?
SELECT
	category
	, AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- What is the total revenue generated for each category?
SELECT 
	p.category
	, SUM(s.price - p.cost) revenue_per_category
FROM gold.dim_products p
LEFT JOIN gold.fact_sales s
	ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY revenue_per_category DESC

-- Find total revenue that is generated by each customer
SELECT
	c.customer_key
	, c.first_name
	, c.last_name
	, SUM(s.sales_amount) AS revenue_generated
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s
	ON c.customer_key = s.customer_key
GROUP BY 	
	c.customer_key
	, c.first_name
	, c.last_name
ORDER BY revenue_generated DESC

-- What is the distribution of sold items across countries?
SELECT
	c.country
	, SUM(s.quantity) AS total_sold_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
	ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC

-- ###############################################
-- Ranking Analysis
-- ###############################################
-- Order the values of dimensions by measures
-- Rank [Dimension] By Aggregation of [Measure]
-- Aggregation - sum, avg, et c.
-- Rank - any ranking window function

-- Which 5 Products generate the highest revenue?
SELECT TOP 5
	p.product_name
	, SUM(s.sales_amount) AS total_sales
FROM gold.dim_products p
LEFT JOIN gold.fact_sales s
	ON p.product_key = s.product_key
GROUP BY p.product_name
ORDER BY total_sales DESC

-- What are the 5 worst-performing products in terms of sales?
SELECT
	p.product_name
	, SUM(s.sales_amount) AS total_sales
FROM gold.dim_products p
LEFT JOIN gold.fact_sales s
	ON p.product_key = s.product_key
GROUP BY p.product_name
HAVING SUM(s.sales_amount) IS NULL
ORDER BY total_sales


SELECT *
FROM (
	SELECT
		p.product_name
		, SUM(s.sales_amount) AS total_sales
		, ROW_NUMBER() OVER(ORDER BY SUM(s.sales_amount) DESC) AS rank_products
	FROM gold.dim_products p
	LEFT JOIN gold.fact_sales s
		ON p.product_key = s.product_key
	GROUP BY p.product_name
	) AS t
WHERE t.rank_products <= 5

-- Find the top 10 custoemrs who have generated the highest revenue
SELECT *
FROM (
	SELECT
		c.customer_key
		, c.first_name
		, c.last_name
		, SUM(s.sales_amount) AS customer_sales
		, ROW_NUMBER() OVER (ORDER BY SUM(s.sales_amount) DESC) AS customer_ranking
	FROM gold.dim_customers c
	LEFT JOIN gold.fact_sales s
		ON c.customer_key = s.customer_key
	GROUP BY 	c.customer_key
		, c.first_name
		, c.last_name
	) AS t
WHERE customer_ranking <= 10

-- Find the 3 customers with the fewest orders places
SELECT *
FROM (
	SELECT
		c.customer_key
		, c.first_name
		, c.last_name
		, SUM(s.sales_amount) AS customer_sales
		, RANK() OVER (ORDER BY SUM(s.sales_amount)) AS customer_ranking
	FROM gold.dim_customers c
	LEFT JOIN gold.fact_sales s
		ON c.customer_key = s.customer_key
	GROUP BY c.customer_key
		, c.first_name
		, c.last_name
	) AS t
WHERE t.customer_ranking <= 3
























